### ISSUE TITLE
No `test_dataloader()` method defined to run `Trainer.test`.

### ISSUE THREAD

**Issue by jihoray** [kswamy15/NLP_Tasks_PyLightning#1]
Hello, Sir.

I am trying to run Bert_NLP_Pytorch_IMDB_v4.ipynb
When I run the cell of Start Training, which has only two lines (trainer.fit and trainer.test), I got No `test_dataloader()` method defined to run `Trainer.test`. MisconfigurationException Error. 

Is there any solution to this error?

Thank you!

**Comment by kswamy15** [comment]
Need to change trainer.test() to trainer.test(dataloaders=imdb_dm) - then this will run properly.  
Used to run without specifying the dataloader as it would take the dataloader from the trainer.fit() specification.  Not sure if pytorch lightning changed something on their function definition.  I will correct this, commit the change and then close the comment.

**Comment by kswamy15** [comment]
Made and committed the change on the notebook.
